apiVersion: apps/v1
kind: Deployment
metadata:
  name: shkube-deployment
  labels:
    app: shkube
spec:
  replicas: 1
  template:
    metadata:
      name: shkube
      labels:
        app: shkube
    spec:
      containers:
      - name: shkube
        image: shkube
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: shkube

---

apiVersion: v1
kind: Service
metadata:
  name: shkube-service
spec:
  selector:
    app: shkube
  ports:
    - port: 80
  type: LoadBalancer